---
- include: get_key.yml

- name: optimization -- short circuit slow call to apt_key
  sudo: yes
  command: apt-key list
  register: apt_key_list
  changed_when: False

- name: add newrelic key to apt-key
  apt_key: file=/root/548C16BF.gpg
  sudo: yes
  when: "'548C16BF' not in apt_key_list.stdout"

- name: sources.list
  template: >
    src=newrelic.list.j2
    dest=/etc/apt/sources.list.d/newrelic.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
