---
- name: download newrelic key
  # https does not work on centos-5
  command: >
    wget -O /root/548C16BF.gpg http://download.newrelic.com/548C16BF.gpg
  args:
    creates: /root/548C16BF.gpg
  sudo: yes
