---
- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install_package_name.yml

- name: Check for license key
  sudo: True
  command: >
    grep license_key={{newrelic_sysmond_license_key}}
    /etc/newrelic/nrsysmond.cfg
  changed_when: False
  ignore_errors: True
  register: grep_result

- name: Add license key to config file
  command: /usr/sbin/nrsysmond-config --set license_key={{newrelic_sysmond_license_key}}
  sudo: True
  notify:
    restart newrelic-sysmond
  when: grep_result|failed
